markdown: kramdown
highlighter: pygments
permalink: blog/:year/:month/:day/:title.html
paginate: 12
paginate_path: page/:num

blog:
    name: ItWd
    description: first to test	
    title: first to test
    url: http://itwd.github.com 
    duoshuo: 
author:
    # Profile links on the left sidebar, leave blank to ignore
    name: Itwd 
    email: InterestWd@163.com 
    weibo:  # weibo ID
    github: wd-moo  # github ID
    logo: http://itwd.github.com/res/img/logo.png

